@host = http://localhost:8081
@baseUrl = /v1
@lead = /context

### Success Lead
POST {{host}}{{baseUrl}}{{lead}}
Content-Type: application/json
Origin: http://localhost:8081
Accept-Language: : es-CO,es;q=0.9
Referer: https://cold-chain-monitoring.com/landing

{
  "vsi": "49960de5880e8c687434170f6476605b8fe4aeb9a28632c7995cf3ba831d9763",
  "vssi": "8ce8551e-8841-48e8-b02a-28b79058133f",
  "vc": {
    "vr": "https://www.google.com/",
    "vp": "https://game.hzone.com/solutions?utm_source=google&utm_medium=cpc&gclid=EAIaIQobChMI7_vR58fD_AIVBQiRCh0vGgSUEAAYASAAEgI_vPD_BwE"
  },
  "vn": {
    "industry": "Pharma",
    "storage_capacity": "500-1000 tons"
  }
}