services:
  ms-acquisition:
    container_name: 
      ms-acquisition
    # Build image with dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: 
      ms-acquisition:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
      - .env.local
      - .env.main
      - .env.test
    restart: 
      unless-stopped
    networks:
      - innosk_network

networks:
  innosk_network:
    external: true